# Site settings
name: lukman Ibrahim
title: lukman
email: lukmanulkaeem1094@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Embedded Software Engineer, C, Device driver, Real-time software, Embedded system, Real-time System, Startups, Raspberry-pi, "
skills: "Embedded Software Engineer in Nigeria, YL"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/hakeem/
  - title: medium
    url: https://medium.com/@hakeem

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
